### ISSUE TITLE
Readme demo crashes against current retext

### ISSUE THREAD

**Issue by bebraw** [wooorm/retext-keywords#10]
Demo: https://github.com/bebraw/keywords-demo .

Crash

```
.../node_modules/retext-keywords/index.js:14
  retext.use(pos);
        ^

TypeError: Cannot read property 'use' of undefined
```

Could it be possible the interface has changed somehow?

**Comment by wooorm** [comment]
Probably, I’ll check, thanks!

**Comment by wooorm** [comment]
Yup, I haven’t updated to the latest retext yet, I’ll publish in a sec!

**Comment by bebraw** [comment]
Ok, on a related note, what's the smartest way to push a collection of Markdown files through it? I could glob and combine. Just wondering if there's a better way.

**Comment by wooorm** [comment]
I’d say first glob, then use [`to-vfile`](https://github.com/vfile/to-vfile)’s `.read` function to create virtual files from file-paths!

**Comment by bebraw** [comment]
Ok, thanks.

**Comment by wooorm** [comment]
👍 

Thanks for raising this issue!
