### ISSUE TITLE
AWS Lambda Insights

### ISSUE THREAD

**Issue by donaldwasserman** [wooorm/retext-keywords#11]
Hi There - 

This is a pretty handy package. I've been using it on the server/local machine just fine.

I've been trying to get this working in AWS lambda, but it keeps seeming to fail, but with no error (the function just times out when trying to `require` the module. 

Looking through the source code, I can't see anything in there that would cause it to do that (eg: native libraries).

Do you have any insights into this?

**Comment by wooorm** [comment]
Hmm, I’m guessing because a dependency, [pos](https://www.npmjs.com/package/pos), is huge!

**Comment by donaldwasserman** [comment]
aaaah so it just takes forever with the limited memory loading that lexicon.js file. 

That's a bummer but thanks for looking into this so quickly!

**Comment by wooorm** [comment]
Yeah sorry about that. If you know a POS tagger with less memory I'd love to hear about it!
