### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by galcivar** [wooorm/retext-keywords#12]
Hi,
What's the algorithm/logic used? I am considering using it to get keywords from text in spanish, would it would?
Thank you!

**Comment by wooorm** [comment]
Unfortunately that would involve lots of work. For more info see https://github.com/wooorm/retext-keywords/issues/7#issuecomment-240176287.

**Comment by galcivar** [comment]
Thank you for the answer. Our team could contribute, but we have no idea where to start, we could achieve something like the pos you shared in #7. Guidance would be needed though.

**Comment by wooorm** [comment]
I suggest first doing research on if there’s a POS tagger for Spanish (in JavaScript). If there is, we can look into things I can help with, but if there isn’t I can’t really help because making those involves lots of research and isn‘t in my capabilities!

**Comment by galcivar** [comment]
@wooorm would some forking of this: https://github.com/nyxtom/salient work?

**Comment by wooorm** [comment]
Hi @galcivar, sorry for the delay! 😬  Yup, seems `salient` would work!

Is there an example [like this](https://github.com/nyxtom/salient#part-of-speech-tagging) for the Spanish part?

If it works anything like that, `retext-pos-es` could be make in the [image of `retest-pos`](https://github.com/wooorm/retext-pos). That’s easy, but maybe the Spanish tagger uses different pos tags than `retext-pos`?
