### ISSUE TITLE
Not working with head version of retext

### ISSUE THREAD

**Issue by roeierez** [wooorm/retext-keywords#2]
I think the problem is that the transformer function that is returned get's file as a second parameter, where at the head version of retext the transformer is called with options (null) instead.

**Comment by wooorm** [comment]
Yes, you are correct. All 1.0.0 versions of the plug-ins only work with the 1.0.0 version of retext (which is still in beta).

For now you should use the rc branch of retext to get retext-keywords working.

Updating all plug-ins takes longer than expected; would you favour a note in the README for now?

**Comment by roeierez** [comment]
Thanks for a quick response. No need for a note.
I don't see the rc branch that you referred me to. I see two branches in retext (master, feature/stable).

**Comment by wooorm** [comment]
`feature/stable`, you can install it with `npm install retext@next` (which will currently install `retext@1.0.0-rc.3`)!

**Comment by roeierez** [comment]
Thanks, this works. like your work.

**Comment by wooorm** [comment]
Great, thanks! :+1:
