### ISSUE TITLE
Stopwords that contain apostrophe are not filtered

### ISSUE THREAD

**Issue by facundoolano** [wooorm/retext-keywords#4]
Hello! Thanks for this project, it's very useful. I've been using it to extract keywords from apps titles and descriptions at Google Play and iTunes, and I've found that some words that I understand that should be considered stopwords, but have apostrophes in them, aren't filtered by this plugin. Some examples are: `it's`, `you'll`, `you're`, `we'll`, `can't`, `won't`, etc.

For now I'm just adding a string replacement for every new case I find before sending it to the processor, but I was wondering if there's a more generic way to filter them out.

**Comment by wooorm** [comment]
Thanks, @facundoolano, for reaching out and using retext-keywords.

Thing is, retext-keywords is based on [parts of speech](https://github.com/wooorm/retext-keywords/blob/d2868e76ea6a40b68b39556607cef9dd59016d99/index.js#L63-L66), not on stopwords.
The POS tags [default to `NN`](https://github.com/dariusk/pos-js/blob/9803735b2b61e42e3f0173e71b0388e638391d6b/POSTagger.js#L46), which makes unknown words eligible for inclusion in the results, which is the reason this occurs.

###### Solving word detection

One fix would be to wait for https://github.com/dariusk/pos-js/issues/21 to be PRd (I believe this is an issue there).

Another would be to create a retext plug-in which expands those elision examples (my preference), or alternatively preprocess the given input and expand them by regexes (easiest):

```js
input.replace(/you[’']ve/, 'you have')/*...*/;
retext.process(input/*, ...*/);
```

The last method should fix this issue, as then the words will be recognised correctly.

###### Solving stop-words

Or, this project could start supporting given configurable stop-words. Would you be interested in working on a PR for that? I could help guide you through the project!

**Comment by facundoolano** [comment]
Thanks for answering. From your explanation it sounds like a plugin that handles the expansions before processing would work better than introducing stopwords. I'll consider working in such plugin in the future, but for now I guess I'll keep on replacing by hand before processing, so I can move forward with my current project.

**Comment by wooorm** [comment]
It’s quite some work, and I’m not *very* interested in working on it currently.
If someone wants this: create a PR on dariusk/pos-js!
