### ISSUE TITLE
Russian language support

### ISSUE THREAD

**Issue by exentrich** [wooorm/retext-keywords#7]
I found retext-latin plugin, but it not improves result. Can you help?

**Comment by wooorm** [comment]
You need a pos tagger like [pos](https://www.npmjs.com/package/pos), but for [Russian](https://github.com/search?utf8=✓&q=pos+tag+russian) (in JavaScript). That’s a pretty hard task to complete though. Once you’ve got that, we can work on [retext-pos](https://github.com/wooorm/retext-pos/blob/master/index.js) to accept a custom POS tagger through it’s options, and we can accept it here and pass it through.

This is *really* hard to do, I doubt it’ll see the day of light so I’m closing this. But feel free to open a new issue/pr if a Russian POS tagger is available!

**Comment by maxmert** [comment]
@wooorm Hi Titus! Thanks for supporting such amazing projects! 🙇‍♂️

There is one POS tagger for Russian: https://github.com/deNULL/Az.js (it's in Russian though). I'd love to work on supporting Russian a bit later, probably will bother you with questions if you don't mind. 😊

**Comment by wooorm** [comment]
@maxmert Sounds cool and feel free to do so! 😉
