### ISSUE TITLE
Version bump on retext-pos dependency?

### ISSUE THREAD

**Issue by pvencill** [wooorm/retext-keywords#8]
I'm trying to bundle retext-keywords using webpack, and apparently it's tripping on the block in retext-pos: 

```js
/*
 * Duo and component / npm and component.
 */

try {
    posjs = require('pos');
} catch (err) {
    /* istanbul ignore next - browser */
    posjs = require('pos-js');
}
```

It looks like webpack sees the `require()` statement inside catch and tries to import that file, which of course doesn't exist since pos-js is not an npm module.  retext-pos v2.0.0 does not appear to have this kind of try..catch in there.

**Comment by wooorm** [comment]
Thanks :)
